# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Charity.create(name: 'Fisher House Foundation', description: 'Fisher House Foundation builds comfort homes where military & veterans families can stay free of charge, while a loved one is in the hospital.', category: 'Veterans & Military', rate: '93%')
Charity.create(name: 'Starlight Children`s Foundation', description: 'Every 30 seconds, a child is diagnosed with a life-threatening medical condition. These children are often scared, confused, lonely and facing serious medical treatments. That’s where Starlight comes in. Starlight programs turn a hospitalized child’s pain, fear and stress into laughter, fun and joy by providing them with the best in entertainment, education and one-of-a-kind experiences — because sick kids are still kids. We believe all children deserve to enjoy the magic, wonder and happiness of childhood, and we’re committed to providing Starlight programs to every seriously ill child in our network of more than 800 children’s hospitals and community health partners across the US.', category: 'Children', rate: '72%')
Charity.create(name: 'Wildlife Conservation Society', description: 'WCS uses science to discover and understand the natural world. This knowledge helps us engage and inspire decision-makers, communities, and millions of supporters to take action with us to protect the wildlife and wild places we all care about.', category: 'Animals', rate: '84%')
Charity.create(name: 'Cancer Research Institute', description: 'Since 1953, we`ve led the field with support for immunotherapy research and clinical trials. Together with our donor, patient, and scientist communities, we continue to fund revolutionary breakthroughs to cure all types of cancer.', category: 'Health, Prevention & Research', rate: '87%')
Charity.create(name: 'Partnership for Drug-Free Kids', description: 'We provide support and guidance to families struggling with their son’s or daughter’s substance use.', category: 'Children', rate: '83%')
Charity.create(name: 'Unbound', description: 'Unbound partners with families living in poverty, empowering them to become self-sufficient and fulfill their desired potential.', category: 'Children', rate: '93%')